GET http://localhost:3001/category?name=hello&description=no

###Login Route
POST http://localhost:3001/category
Content-Type: application/json

{
  "name": "hekdddelekej",
  "description": "1234"
}


###Register Route
POST http://localhost:3001/category
Content-Type: application/json

{
  "name": "hello9091919"
}
###Valid Check
POST http://localhost:3001/validate-category-name
Content-Type: application/json

{
  "name": "hekdddelekej"
}

###Register Route
PUT http://localhost:3001/category/30
Content-Type: application/json

{
  "name": "yourjstruly267",
  "description": "1234"
}

###Logout Route
DELETE http://localhost:3001/category/30
Content-Type: application/json