GET http://localhost:3001/category

###Login Route
POST http://localhost:3001/category
Content-Type: application/json

{
  "name": "jjh7jg"
}


###Register Route
POST http://localhost:3001/category
Content-Type: application/json

{
  "name": "hello9091919"
}
###Valid Check
POST http://localhost:3001/validate-category-name
Content-Type: application/json

{
  "name": "hello9091919"
}

###Register Route
PUT http://localhost:3001/category/20
Content-Type: application/json

{
  "name": "yourstruly267",
  "description": "1234"
}

###Logout Route
DELETE http://localhost:3001/category/0
Content-Type: application/json